[alembic]
# 현재 설정 파일이 있는 디렉터리를 기준으로 마이그레이션 경로를 해석한다.
script_location = %(here)s/migrations
sqlalchemy.url = sqlite+pysqlite:///./private-cloud-development.db

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
